// GlobalComponents for Volar
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('panda-ui')['Avatar']
    Badge: typeof import('panda-ui')['Badge']
    Button: typeof import('panda-ui')['Button']
    ButtonGroup: typeof import('panda-ui')['ButtonGroup']
    Card: typeof import('panda-ui')['Card']
    CardBody: typeof import('panda-ui')['CardBody']
    CardDescription: typeof import('panda-ui')['CardDescription']
    CardFooter: typeof import('panda-ui')['CardFooter']
    CardHeader: typeof import('panda-ui')['CardHeader']
    CardTitle: typeof import('panda-ui')['CardTitle']
    Checkbox: typeof import('panda-ui')['Checkbox']
    Col: typeof import('panda-ui')['Col']
    CollapseTransition: typeof import('panda-ui')['CollapseTransition']
    ContextMenu: typeof import('panda-ui')['ContextMenu']
    DatePicker: typeof import('panda-ui')['DatePicker']
    Dropdown: typeof import('panda-ui')['Dropdown']
    DropdownItem: typeof import('panda-ui')['DropdownItem']
    DropdownList: typeof import('panda-ui')['DropdownList']
    EmojiPicker: typeof import('panda-ui')['EmojiPicker']
    Filter: typeof import('panda-ui')['Filter']
    FilterGroup: typeof import('panda-ui')['FilterGroup']
    FullScreen: typeof import('panda-ui')['FullScreen']
    Icon: typeof import('panda-ui')['Icon']
    Input: typeof import('panda-ui')['Input']
    Label: typeof import('panda-ui')['Label']
    Masker: typeof import('panda-ui')['Masker']
    Menu: typeof import('panda-ui')['Menu']
    Message: typeof import('panda-ui')['Message']
    Modal: typeof import('panda-ui')['Modal']
    Option: typeof import('panda-ui')['Option']
    Panel: typeof import('panda-ui')['Panel']
    PanelGroup: typeof import('panda-ui')['PanelGroup']
    PanelResizeHandle: typeof import('panda-ui')['PanelResizeHandle']
    Popper: typeof import('panda-ui')['Popper']
    Portal: typeof import('panda-ui')['Portal']
    Radio: typeof import('panda-ui')['Radio']
    Row: typeof import('panda-ui')['Row']
    ScrollArea: typeof import('panda-ui')['ScrollArea']
    Select: typeof import('panda-ui')['Select']
    Sheet: typeof import('panda-ui')['Sheet']
    Switch: typeof import('panda-ui')['Switch']
    Tab: typeof import('panda-ui')['Tab']
    Tabs: typeof import('panda-ui')['Tabs']
    TabsList: typeof import('panda-ui')['TabsList']
    TabsPane: typeof import('panda-ui')['TabsPane']
    TabsTrigger: typeof import('panda-ui')['TabsTrigger']
    Tag: typeof import('panda-ui')['Tag']
    Tooltip: typeof import('panda-ui')['Tooltip']
  }

  interface ComponentCustomProperties {}
}

export {}
