/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlApp: typeof import('./.vitepress/vitepress/components/bl-app.vue')['default']
    BlContent: typeof import('./.vitepress/vitepress/components/bl-content.vue')['default']
    BlDocContent: typeof import('./.vitepress/vitepress/components/bl-doc-content.vue')['default']
    BlFooter: typeof import('./.vitepress/vitepress/components/bl-footer.vue')['default']
    BlHeader: typeof import('./.vitepress/vitepress/components/bl-header.vue')['default']
    BlHomepage: typeof import('./.vitepress/vitepress/components/bl-homepage.vue')['default']
    BlSidebar: typeof import('./.vitepress/vitepress/components/bl-sidebar.vue')['default']
    BlSiderbar: typeof import('./.vitepress/vitepress/components/bl-siderbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wave: typeof import('./.vitepress/vitepress/components/wave/wave.vue')['default']
  }
}
