/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlApp: typeof import('./.vitepress/vitepress/components/bl-app.vue')['default']
    BlComponentDemo: typeof import('./.vitepress/vitepress/components/panda-ui/demo/bl-component-demo.vue')['default']
    BlContent: typeof import('./.vitepress/vitepress/components/bl-content.vue')['default']
    BlDemo: typeof import('./.vitepress/vitepress/components/bl-demo.vue')['default']
    BlDocContent: typeof import('./.vitepress/vitepress/components/bl-doc-content.vue')['default']
    BlFooter: typeof import('./.vitepress/vitepress/components/bl-footer.vue')['default']
    BlHeader: typeof import('./.vitepress/vitepress/components/bl-header.vue')['default']
    BlHomepage: typeof import('./.vitepress/vitepress/components/panda-ui/bl-homepage.vue')['default']
    BlSelectPro: typeof import('./.vitepress/vitepress/components/bl-select-pro.vue')['default']
    CardStack: typeof import('./.vitepress/vitepress/components/card-stack.vue')['default']
    CtHomepage: typeof import('./.vitepress/vitepress/components/chat/ct-homepage.vue')['default']
    DemoFour: typeof import('./.vitepress/vitepress/components/panda-ui/home-navbar/demoFour/index.vue')['default']
    DemoOne: typeof import('./.vitepress/vitepress/components/panda-ui/home-navbar/demoOne/index.vue')['default']
    DemoThree: typeof import('./.vitepress/vitepress/components/panda-ui/home-navbar/demoThree/index.vue')['default']
    DemoTwo: typeof import('./.vitepress/vitepress/components/panda-ui/home-navbar/demoTwo/index.vue')['default']
    PdHomepage: typeof import('./.vitepress/vitepress/components/panda/pd-homepage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./.vitepress/vitepress/components/common/sidebar/sidebar.vue')['default']
    SidebarLink: typeof import('./.vitepress/vitepress/components/common/sidebar/sidebar-link.vue')['default']
    SourceCode: typeof import('./.vitepress/vitepress/components/source-code.vue')['default']
    SsoHomepage: typeof import('./.vitepress/vitepress/components/sso/sso-homepage.vue')['default']
    SwitchProject: typeof import('./.vitepress/vitepress/components/common/switch-project/index.vue')['default']
    TableContent: typeof import('./.vitepress/vitepress/components/common/doc-content/table-content.vue')['default']
  }
}
